services:
  # Core Go API
  api:
    build:
      context: .
      dockerfile: deployments/Dockerfile.go
    ports:
      - "8080:8080"
    environment:
      - WORKER_URL=http://worker:8001
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
      - ./pipelines:/app/pipelines
    depends_on:
      - redis
      - worker

  # Python NLP Worker
  worker:
    build:
      context: ./worker
      dockerfile: ../deployments/Dockerfile.python
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./worker:/app/worker
      - ./data:/app/data

  # UI Next.js (disponível em v0.2)
  ui:
    build:
      context: ./ui
      dockerfile: ../deployments/Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - api
    profiles:
      - ui

  # Redis (jobs queue)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
