blank_issues_enabled: false
contact_links:
  - name: 📌 Roadmap do projeto
    url: https://github.com/yourorg/sapientia/blob/main/ROADMAP.md
    about: Consulte a visão e as versões planejadas antes de abrir uma issue
